version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: kevin
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: modbusdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: modbus_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    image: node:23.3.0
    container_name: modbus_backend
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: sh -c "npm install && npm run dev"

  sensor:
    image: node:23.3.0
    container_name: modbus_sensor
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: sh -c "npm install && npm run sensor"

  client:
    image: node:23.3.0
    container_name: modbus_client
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - sensor
    command: sh -c "npm install && npm run client"

volumes:
  pgdata:
